set -e
TARGET="localhost"
SSH_PORT="8222"
USER="admin"
KEY_FILE="VBOX_KEY"
MYSQL_USER="acit4640"
MYSQL_USER_PASS="P@ssw0rd"
MYSQL_DATABASE="assignment"
SSH="ssh -i ${KEY_FILE} -p ${SSH_PORT} ${USER}@${TARGET}"
$SSH "mysql -u root" << EOF
CREATE DATABASE ${MYSQL_DATABASE};
CREATE USER ${MYSQL_USER} IDENTIFIED BY '${MYSQL_USER_PASS}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO ${MYSQL_USER}@'%';
USE ${MYSQL_DATABASE};
CREATE TABLE IF NOT EXISTS students(name VARCHAR(225) NOT NULL, student_id VARCHAR(9) NOT NULL, PRIMARY KEY(student_id));
INSERT INTO students (student_id, name) VALUES ("A00816145", "Bowen");
EOF
