---
- hosts: localhost
  tasks:
    - name: aws role
      include_role:
        name: aws
      tags:
        - provision
        - info
        - clean
- hosts: aws_ec2
  tasks:
    - name: Run database role
      include_role:
        name: database
      tags:
        - provision
        - application
    - name: Run backend role
      include_role:
        name: backend
      tags:
        - provision
        - application
    - name: Run frontend role
      include_role:
        name: frontend
      tags:
        - provision
        - application
    - name: Run nginx role
      include_role: 
        name: nginx
      tags:
        - provision
        - application
    - name: Collect facts about system services
      service_facts:
      register: services_state
      tags:
        - info
    - name: Display status of nginx service
      debug:
        var: services_state.ansible_facts.services['nginx.service']
      when: services_state.ansible_facts.services['nginx.service'] is defined
      tags:
        - info
    - name: Display status of backend service
      debug:
        var: services_state.ansible_facts.services['backend.service']
      when: services_state.ansible_facts.services['backend.service'] is defined
      tags:
        - info
    - name: Display status of mysqld service
      debug:
        var: services_state.ansible_facts.services['mysqld.service']
      when: services_state.ansible_facts.services['mysqld.service'] is defined
      tags:
        - info
